### PR TITLE
README: Add pluto link

### PR DESCRIPTION
**Pull request by fonsp**
Hi! I love this package! Adding the link should make it easier for people to find Handcalcs.jl online

https://github.com/user-attachments/assets/aaf1d012-0c31-4c78-bd35-185fd6be2705

### CODE REVIEW

**Comment by co1emi11er2** [comment]
Cool! I am glad you like the package!

**Comment by fonsp** [comment]
I love it!!

Actually if you are interested, you could write a short notebook for https://github.com/JuliaPluto/featured ! You can explain a mathematical idea, or you can showcase the features of Handcalcs.jl! I think the package is quite useful for teachers using Pluto and I think it is easy to use, so I think many people would benefit from the featured notebook :)

You can just make a draft PR to https://github.com/JuliaPluto/featured with a rough notebook, or you can email me if you would like to discuss ideas

**Comment by co1emi11er2** [comment]
Oh yeah that would be awesome!! I will see what I can come up with, and I'll get back to you!

**Comment by fonsp** [comment]
Hey Cole! Did you have time to look into a notebook? :)

**Comment by co1emi11er2** [comment]
Hey @fonsp! I should have some time today. Did you get a chance to look at the pull request I submitted to the featured pluto notebook repository?

**Comment by co1emi11er2** [comment]
Sorry I misread your message. Yes I did end up creating a notebook. I will add a message to the pull request on the featured repository.

**Pull request merged**
